In [1]:
# Replay of https://www.youtube.com/watch?v=C4N3_XJJ-jU&t=613s
# Import and clean up the data
# Data from https://archive.ics.uci.edu/static/public/45/heart+disease.zip

In [2]:
data <- read.csv(file = "./processed.cleveland.data", header = FALSE)

In [3]:
head(data)

  V1 V2 V3 V4  V5  V6 V7 V8  V9 V10 V11 V12 V13 V14
1 63 1  1  145 233 1  2  150 0  2.3 3   0.0 6.0 0
2 67 1  4  160 286 0  2  108 1  1.5 2   3.0 3.0 2
3 67 1  4  120 229 0  2  129 1  2.6 2   2.0 7.0 1
4 37 1  3  130 250 0  0  187 0  3.5 3   0.0 3.0 0
5 41 0  2  130 204 0  2  172 0  1.4 1   0.0 3.0 0
6 56 1  2  120 236 0  0  178 0  0.8 1   0.0 3.0 0

In [4]:
colnames(data) <- c("age", "sex", "cp", "trestbps", "chol", "fbs", "restecg", "thalach", "exang",
                    "oldpeak", "slope", "ca", "thal", "hd")

In [5]:
head(data)

  age sex cp trestbps chol fbs restecg thalach exang oldpeak slope ca  thal hd
1 63  1   1  145      233  1   2       150     0     2.3     3     0.0 6.0  0
2 67  1   4  160      286  0   2       108     1     1.5     2     3.0 3.0  2
3 67  1   4  120      229  0   2       129     1     2.6     2     2.0 7.0  1
4 37  1   3  130      250  0   0       187     0     3.5     3     0.0 3.0  0
5 41  0   2  130      204  0   2       172     0     1.4     1     0.0 3.0  0
6 56  1   2  120      236  0   0       178     0     0.8     1     0.0 3.0  0

In [6]:
str(data) # describes the structure of the data

'data.frame':	303 obs. of  14 variables:
 $ age     : num  63 67 67 37 41 56 62 57 63 53 ...
 $ sex     : num  1 1 1 1 0 1 0 0 1 1 ...
 $ cp      : num  1 4 4 3 2 2 4 4 4 4 ...
 $ trestbps: num  145 160 120 130 130 120 140 120 130 140 ...
 $ chol    : num  233 286 229 250 204 236 268 354 254 203 ...
 $ fbs     : num  1 0 0 0 0 0 0 0 0 1 ...
 $ restecg : num  2 2 2 0 2 0 2 0 2 2 ...
 $ thalach : num  150 108 129 187 172 178 160 163 147 155 ...
 $ exang   : num  0 1 1 0 0 0 0 1 0 1 ...
 $ oldpeak : num  2.3 1.5 2.6 3.5 1.4 0.8 3.6 0.6 1.4 3.1 ...
 $ slope   : num  3 2 2 3 1 1 3 1 2 3 ...
 $ ca      : chr  "0.0" "3.0" "2.0" "0.0" ...
 $ thal    : chr  "6.0" "3.0" "7.0" "3.0" ...
 $ hd      : int  0 2 1 0 0 0 3 0 2 1 ...

In [7]:
data[data == "?"] <- NA # Change the "?" to NAs

In [8]:
data[data == "?"]

[1] NA NA NA NA NA NA

In [9]:
data[data == "NA"]

[1] NA NA NA NA NA NA

In [10]:
data[data$sex == 0,]$sex <- "F" # convert the 0s in sex to F
data[data$sex == 1,]$sex <- "M" # convert the 1s in sex to M
data$sex <- as.factor(data$sex)

In [35]:
str(data)

'data.frame':	303 obs. of  14 variables:
 $ age     : num  63 67 67 37 41 56 62 57 63 53 ...
 $ sex     : Factor w/ 2 levels "F","M": 2 2 2 2 1 2 1 1 2 2 ...
 $ cp      : num  1 4 4 3 2 2 4 4 4 4 ...
 $ trestbps: num  145 160 120 130 130 120 140 120 130 140 ...
 $ chol    : num  233 286 229 250 204 236 268 354 254 203 ...
 $ fbs     : num  1 0 0 0 0 0 0 0 0 1 ...
 $ restecg : num  2 2 2 0 2 0 2 0 2 2 ...
 $ thalach : num  150 108 129 187 172 178 160 163 147 155 ...
 $ exang   : num  0 1 1 0 0 0 0 1 0 1 ...
 $ oldpeak : num  2.3 1.5 2.6 3.5 1.4 0.8 3.6 0.6 1.4 3.1 ...
 $ slope   : num  3 2 2 3 1 1 3 1 2 3 ...
 $ ca      : chr  "0.0" "3.0" "2.0" "0.0" ...
 $ thal    : chr  "6.0" "3.0" "7.0" "3.0" ...
 $ hd      : int  0 2 1 0 0 0 3 0 2 1 ...

In [46]:
levels(data$sex)

[1] "F" "M"